import { useEffect, useState } from 'react'
import api from '../api'

const blank={serviceName:'',planName:'',category:'AI',description:'',homepageUrl:'',monthlyPrice:0,yearlyPrice:0,usageLimit:'',usageUnit:'',active:true}
const categories={AI:'AI',PRODUCTIVITY:'생산성',CAREER:'취업',DEVELOPMENT:'개발',ENTERTAINMENT:'엔터테인먼트'}
export default function Services(){
 const [items,setItems]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[error,setError]=useState('')
 const load=()=>api.get('/services').then(r=>setItems(r.data)).catch(()=>setError('서비스 목록을 불러오지 못했습니다.'));useEffect(load,[])
 const submit=async e=>{e.preventDefault();const body={...form,monthlyPrice:Number(form.monthlyPrice),yearlyPrice:Number(form.yearlyPrice),usageLimit:form.usageLimit===''?null:Number(form.usageLimit)};try{editing?await api.put(`/services/${editing}`,body):await api.post('/services',body);setForm(blank);setEditing(null);load()}catch{setError('서비스를 저장하지 못했습니다.')}}
 const edit=x=>{setEditing(x.id);setForm({...x,usageLimit:x.usageLimit??''})}
 return <div><header className="page-head"><div><h1>서비스 관리</h1><p>구독 중이거나 관심 있는 외부 서비스와 플랜 정보를 등록합니다.</p></div></header>{error&&<div className="error-banner">{error}</div>}
 <form className="form-panel form-grid" onSubmit={submit}><input placeholder="서비스명 (예: ChatGPT)" value={form.serviceName} onChange={e=>setForm({...form,serviceName:e.target.value})} required/><input placeholder="플랜명 (예: Plus)" value={form.planName} onChange={e=>setForm({...form,planName:e.target.value})} required/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{Object.entries(categories).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input type="number" placeholder="월 가격" value={form.monthlyPrice} onChange={e=>setForm({...form,monthlyPrice:e.target.value})}/><input type="number" placeholder="연 가격" value={form.yearlyPrice} onChange={e=>setForm({...form,yearlyPrice:e.target.value})}/><input type="number" placeholder="사용 한도 (선택)" value={form.usageLimit} onChange={e=>setForm({...form,usageLimit:e.target.value})}/><input placeholder="한도 단위 (MESSAGES, GB 등)" value={form.usageUnit||''} onChange={e=>setForm({...form,usageUnit:e.target.value})}/><input placeholder="서비스 설명" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/><div className="form-actions"><button className="btn">{editing?'서비스 수정':'서비스 추가'}</button>{editing&&<button type="button" className="btn secondary" onClick={()=>{setEditing(null);setForm(blank)}}>취소</button>}</div></form>
 <div className="card-grid">{items.map(x=><article className="item-card" key={x.id}><div className="service-cell"><span className="service-logo">{x.serviceName[0]}</span><div><h3>{x.serviceName}</h3><small>{x.planName}</small></div></div><p>{x.description||'설명 없음'}</p><div className="item-meta"><span>카테고리</span><strong>{categories[x.category]||x.category}</strong></div><div className="item-meta"><span>월 / 연 가격</span><strong>₩{Number(x.monthlyPrice).toLocaleString()} / ₩{Number(x.yearlyPrice).toLocaleString()}</strong></div><div className="item-meta"><span>사용 한도</span><strong>{x.usageLimit?`${x.usageLimit} ${x.usageUnit||''}`:'제한 없음'}</strong></div><div className="item-actions"><button className="btn small secondary" onClick={()=>edit(x)}>수정</button><button className="btn small danger" onClick={async()=>{if(confirm('서비스를 삭제할까요?')){try{await api.delete(`/services/${x.id}`);load()}catch{setError('구독이 연결된 서비스는 삭제할 수 없습니다.')}}}}>삭제</button></div></article>)}</div></div>
}
